config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, only: %i[ edit update index new create ]
  resources :users, only: %i[ show ]

  put 'accept/invitation/:invitation_id', controller: :users, action: 'accept_invitation', as: :accept_invitation

  resources :events do
    member do
      delete 'unattend'
      post 'invite/:user_id', action: 'invite', as: :invite_user
    end

    resources :attendances, only: %i[ destroy create ]

  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User",
                       foreign_key: "creator_id"

  has_many :attendances, foreign_key: "attendeed_event_id", class_name: "EventAttendance", dependent: :destroy

  has_many :attendees, through: :attendances

  has_many :invitations, dependent: :destroy

  scope :past, -> { where('date_time < ?', Date.today).order(created_at: :desc) }
  scope :future, -> { where('date_time > ?', Date.today).order(created_at: :desc) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attendeed_event, class_name: "Event"
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  scope :waiting, -> { where(status: false)}
  scope :accepted, -> { where(status: true)}

  belongs_to :user
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event",
                            foreign_key: "creator_id"

  has_many :event_attendances, foreign_key: "attendee_id", dependent: :destroy

  has_many :attendeed_events, through: :event_attendances


  has_many :invitations, class_name: "Invitation", foreign_key: "user_id", dependent: :destroy
  has_many :invites, class_name: "Invitation", foreign_key: "receiver_id", dependent: :destroy

  def event_owner?(event_id:)
    return true if Event.where(id: event_id, creator_id: self.id).exists?

    false
  end

  def page_owner?(page_id:)
    return true if self.id == page_id

    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @attendance = EventAttendance.new(attendee_id: current_user.id, attendeed_event_id: params[:event_id])

    if @attendance.save
      redirect_to events_path, notice: "Nice! You're in for now, good luck."
    else
      redirect_to events_path, alert: 'Something goes wrong, try do it again.'
    end

  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
    @event = Event.new
  end

  def destroy
    event = Event.find(params[:id])

    if current_user.event_owner?(event_id: event.id) && event.destroy
      redirect_to events_path, notice: "Your event has been destroyed!"
    else
      redirect_to events_path, alert: "You're not the post' owner!"
    end
  end

  def edit
    @event = Event.find(params[:id])

    if @event.creator_id != current_user.id
      flash[:alert] = "You're not the post owner!"
      redirect_to events_path
    end

  end

  def unattend
    @event = Event.find(params[:id])
    @attendeed_event = EventAttendance.find_by(attendee_id: current_user.id, attendeed_event_id: @event.id)

    @attendeed_event.destroy

    redirect_to @event, notice: "Now you're not in the event attendance list."
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: 'Your post has been editted with success!'
    else
      flash.now[:alert] = 'Something goes wrong, please try do it again.'
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all
  end

  def invite
    unless current_user.event_owner?(event_id: params[:id])
      redirect_to event_path(params[:id]), alert: "You're not the event's owner!"
      return false
    end

    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])

    @invite = current_user.invitations.build(receiver_id: @user.id, event_id: @event.id)

    if @invite.save
      redirect_to event_path(@event), notice: "You've invited the user #{@user.email}!"
    else
      redirect_to event_path(@event), alert: "Something goes wrong, try do it again."
    end
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to events_path, notice: "Your event have been created."
    else
      flash.now[:alert] = "Some inputs are invalid, please check it out!"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date_time)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def accept_invitation
    @invitation = Invitation.find(params[:invitation_id])
    unless current_user.page_owner?(page_id: @invitation.receiver_id)
      redirect_to user_path(@invitation.receiver_id), alert: "You're not that user!"

      return false
    end
    @event = Event.find(@invitation.event_id)
    @attendance = @event.attendances.build(attendee_id: @invitation.receiver_id)

    if @invitation.update(status: true) && @attendance.save
      redirect_to user_path(@invitation.receiver_id), notice: "Now, you're in the event!"
    else
      redirect_to root_path, alert: 'Something goes wrong, please try do it again.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def in_attendance?(user: nil, event_id: nil)
    user_attendeed_events = user.attendeed_events.all.includes(:creator)
    user_attendeed_events.each do |attendeed_event|
      return true if attendeed_event.id == event_id
    end
    #user_attendance_query = EventAttendance.where(attendee_id: user_id, attendeed_event_id: event_id).first
    #return true if user_attendance_query

    false
  end
end

app/views/events/edit.html.erb
<%= render partial: 'shared/header' %>
<% if flash[:notice] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= notice %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>


<% if flash[:alert] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= alert %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>

<section class="container d-flex flex-column align-items-center justify-content-center">
  <div class="row w-100 mt-5 d-flex justify-content-center">
    <div class="col-xl-6 col-lg-8 col-md-10 col-sm-12">
      <%= form_with model: @event do |form| %>
        <div class="field my-2">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="field my-2">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, style: "resize: none;", rows: 6, class: "form-control" %>
        </div>
        <div class="field my-2">
          <%= form.label :date_time, class: "form-label" %><br/>
          <%= form.datetime_local_field :date_time, class: "form-control" %>
        </div>
        <%= form.submit 'Save it', class: "btn btn-primary px-5 my-2" %>
        <%= link_to 'Cancel', event_path(@event),class: 'text-danger btn btn-link' %>
      <% end %>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<%= render partial: 'shared/header' %>
<% if flash[:notice] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= notice %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>


<% if flash[:alert] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= alert %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>
<section class="container mt-5">
  <div class="row">
    <article class="col">
      <% Event.future.each do |event| %>
        <div class="card my-2">
          <div class="card-header"><%= event.date_time.strftime("%d/%m/%Y - %I:%M %p") %></div>
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <p class="card-text"><%= event.description %></p>
            <% if event.creator_id == current_user.id %>
              By: <b class="card-text"><%= event.creator.email %> <span class="text-muted">(You)</span></b><br/>
            <% else %>
              By: <b class="card-text"><%= event.creator.email %></b><br/>
            <% end %>

            <% if EventAttendance.exists?(attendee_id: current_user.id, attendeed_event_id: event.id) %>
              <div class="d-flex my-2">
                <%= button_to 'Cancel', unattend_event_path(event), class: 'btn btn-danger px-5', method: :delete %>
                <%= link_to '👁 Show', event_path(event), class: 'text-decoration-none py-2 btn btn-link' %>
              </div>
            <% elsif event.creator_id == current_user.id %>
              <div class="d-flex">
                <%= link_to '👁 Show', event_path(event), class: 'text-decoration-none py-2 btn-link' %>
              </div>
            <% else %>
              <div class="d-flex my-2">
                <%= button_to 'Get in', event_attendances_path(event), method: :post, class: 'px-5 btn btn-primary px-4' %>
                <%= link_to '👁 Show', event_path(event), class: 'text-decoration-none py-2 btn btn-link' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>

      <% Event.past.each do |event| %>
        <div class="card my-2">
          <div class="card-header text-decoration-line-through"><%= event.date_time.strftime("%d/%m/%Y - %I:%M %p") %></div>
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <p class="card-text"><%= event.description %></p>
            <% if event.creator_id == current_user.id %>
              By: <b class="card-text"><%= event.creator.email %> <span class="text-muted">(You)</span></b><br/>
            <% else %>
              By: <b class="card-text"><%= event.creator.email %></b><br/>
            <% end %>
            </div>
          </div>
      <% end %>
    </article>
  </div>
</section>

app/views/events/new.html.erb
<%= render partial: 'shared/header' %>

<% if flash[:notice] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= notice %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>


<% if flash[:alert] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= alert %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>

<section class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10 my-5">
      <%= form_with model: @event do |form| %>
        <div class="field my-2">
          <%= form.label :title, class: 'form-label' %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="field my-2">
          <%= form.label :description, class: 'form-label' %>
          <%= form.text_area :description, rows: 6, style: 'resize: none;', class: 'form-control' %>
        </div>

        <div class="field my-2">
          <%= form.label :date_time, class: 'form-label' %>
          <%= form.datetime_local_field :date_time, class: 'form-control' %>
        </div>
        <%= form.submit 'Touch it', class: 'btn btn-primary px-5' %>
        <%= link_to 'Cancel', root_path, class: 'btn btn-link text-secondary' %>
      <% end %>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<%= render partial: 'shared/header' %>

<% if flash[:notice] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= notice %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>


<% if flash[:alert] %>
  <span data-controller="alert" class="d-flex justify-content-between alert alert-warning" role="alert">
    <%= alert %> <button type="button" data-action="alert#hide" class="btn-close" aria-label="Close"></button>
  </span>
<% end %>

<section class="container mt-5">
  <article class="row">
    <div class="col">
      <div class="card">
          <div class="card-header">
            <%= @event.date_time.strftime("%d/%m/%Y - %I:%M %p") %>
            <div class="d-flex mt-2 gap-2">
              <%= link_to 'Edit it', edit_event_path(@event), class: 'btn btn-outline-primary' %>
              <%= button_to 'Destroy it', event_path(@event), method: :delete, class: 'btn btn-outline-danger' %>
            </div>
          </div>
          <div class="card-body">
          <h3 class="card-title"><%= @event.title %></h3>
          <p class="card-text"><%= @event.creator.email %></p>

          <p class="card-text fs-6"><%= @event.description %></p>
          <ul class="list-group">
            Event Attendees:
            <% @event.attendees.each do |attendee| %>
              <%= link_to attendee.email, user_path(attendee), class: "list-group-item" %>
            <% end %>
          </ul>

        </div>
      </div>

    <article class="border p-2 mt-4 d-flex flex-column gap-2">
      <span>Invite some users.</span>
      <% @users.each do |user| %>
        <% next if @event.creator_id == user.id || current_user.id == user.id %>
        <% next if EventAttendance.where(attendee_id: user.id, attendeed_event_id: @event.id).exists? %>

        <% unless Invitation.where(user_id: @event.creator_id, receiver_id: user.id, event_id: @event.id, status: false).exists? %>
          <div class="p-2 border justify-content-between d-flex">
            <span><%= user.email %></span>
            <%= button_to 'Invite', invite_user_event_path(@event.id, user.id), style: 'border: none; background-color: white;', class: 'btn-link' %>
          </div>
        <% end %>
      <% end %>
    </article>
    </div>
  </article>
</section>

app/views/home/index.html.erb
<section class="pb-5 border-1 border-bottom">
<%= render partial: 'shared/header' %>
  <% if flash[:notice] %>
    <p class="alert alert-primary" role="alert"><%= notice %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert alert-warning" role="alert"><%= alert %></p>
  <% end %>
  <div class="container">
    <section class="row">
        <article class="col-9 d-flex flex-column align-items-center flex-start-origin">
          <div>
            <h1 class="display-2 fw-bold">Fastent</h1>
            <h3 class="text-muted fw-normal">Making your events with a smile, because it's easy, lightweight and very intuitive for you make great events without headache.</h3>
            <div class="mt-4">
              <%= link_to '↳ Sign up now!', new_user_registration_path, class: 'fw-bold btn btn-primary large btn-lg px-4' %>
              <%= link_to 'Log in', new_user_session_path, class: 'btn btn-link btn-lg' %>
            </div>
          </div>
        </article>
      </div>
    </section>
  </div>

  <section class="container mt-5">
    <div class="row mb-5 pb-4 d-flex align-items-center">
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
    </div>

    <div class="row d-flex align-items-center">
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
      <article class="col-4 gap-2 d-flex justify-content-center align-items-center">
        <div>
          <h2>Fast 🚀</h2>
          <h5 class="text-muted">It's really fast and lightweight.</h5>
        </div>
      </article>
    </div>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fastent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #f8f9fa;" class="d-flex flex-column min-vh-100">

    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="mt-auto">

  <footer class="bg-dark text-center text-white">
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Fastent:
    <a class="text-white" href="https://mdbootstrap.com/"> wmw.fastent.lupe</a>
  </div>
  <!-- Copyright -->
</footer>

</div>
<!-- End of .container -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <a class="navbar-brand" href="/">Fastent</a>
    <ul class="navbar-nav d-flex flex-row gap-4 me-auto mt-2 mt-lg-0">

    </ul>
    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav me-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
          <li class="nav-item active">
            <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Events', events_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'New Event', new_event_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= button_to 'Log Out', destroy_user_session_path, class: 'nav-link btn', method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<%= render partial: 'shared/header' %>
<section class="container mt-5 d-flex flex-column">
    <article class="card my-2">
      <div class="card-header">Profile</div>
      <div class="card-body">
        <span class="card-text">Email: <%= @user.email %></span>
      </div>
    </article>

    <article class="card mt-4">
      <div class="card-header">Mail Box:</div>
      <ul class="list-group">
        <% @user.invites.each do |invitation| %>
          <% unless invitation.status %>
              <li class="list-group-item d-flex flex-column">
                <span class="card-text">Invitation by: <%= User.find(invitation.user_id).email %></span>
                <span class="card-text">Event: <%= Event.find(invitation.event_id).title %></span>
              <%= button_to 'Accept', accept_invitation_path(invitation.id), method: :put, class: 'btn btn-outline-primary mt-2' %>
            </li>
            <% end %>
        <% end %>
      </ul>
    </article>
</section>